# Generated by Django 3.1.7 on 2021-04-12 16:38

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='token',
            field=mirage.fields.EncryptedTextField(max_length=100),
        ),
    ]
