# Generated by Django 3.1.7 on 2021-04-12 19:39

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210412_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='gh_token',
            field=mirage.fields.EncryptedTextField(default='testtoken', max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='token',
            field=mirage.fields.EncryptedTextField(default='testtoken', max_length=100),
        ),
    ]
